version: '3.4'

services:
  bot:
    container_name: youtube-downloader
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    env_file: .env
    image: hub.virtual-it.ru/youtube-downloader:latest
    volumes:
      - ./video/:/video
      - ./log:/var/log
    restart: always
